# Generated by Django 3.0.1 on 2020-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('degree_of_study', models.CharField(max_length=30)),
                ('year_of_study', models.PositiveSmallIntegerField()),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('GPAX', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
